import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const BLUE='#2563EB', DEEP='#0F2A5F', LIGHT='#EFF6FF';
const destinations=[{name:'Ella',note:'Mountains & views',icon:'leaf-outline' as const},{name:'Galle',note:'Coast & heritage',icon:'sunny-outline' as const},{name:'Kandy',note:'Culture & nature',icon:'flower-outline' as const}];
export default function HomeScreen(){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
<View style={s.header}><View style={s.avatar}><Text style={s.avatarText}>M</Text></View><View style={{flex:1}}><Text style={s.eyebrow}>GOOD AFTERNOON</Text><Text style={s.heading}>Where to next?</Text></View><TouchableOpacity style={s.iconButton}><Ionicons name="notifications-outline" size={22}/></TouchableOpacity></View>
<View style={s.search}><Ionicons name="search" size={21} color="#64748B"/><TextInput placeholder="Search a destination" placeholderTextColor="#94A3B8" style={s.searchInput}/><TouchableOpacity style={s.filter}><Ionicons name="options-outline" size={19} color="white"/></TouchableOpacity></View>
<View style={s.sectionHead}><Text style={s.sectionTitle}>Upcoming trip</Text><Text style={s.link}>View all</Text></View>
<TouchableOpacity activeOpacity={.9} onPress={()=>router.push('/trip')}><LinearGradient colors={[BLUE,DEEP]} start={{x:0,y:0}} end={{x:1,y:1}} style={s.hero}><View style={s.heroTop}><View style={s.pill}><Ionicons name="time-outline" color="white" size={15}/><Text style={s.pillText}> 8 days to go</Text></View><Ionicons name="ellipsis-horizontal" color="white" size={24}/></View><View style={{flex:1}}/><Text style={s.heroLabel}>SRI LANKA</Text><Text style={s.heroTitle}>Ella Weekend</Text><Text style={s.heroMeta}>Oct 13 – Oct 15   •   4 travelers</Text><View style={s.routeMini}><Ionicons name="location" color="white" size={15}/><Text style={s.routeText}>Colombo → Kandy → Ella</Text><Text style={s.routeKm}>247 km</Text></View><View style={s.heroBottom}><View style={s.faces}>{['M','S','N','+1'].map(x=><View key={x} style={s.face}><Text style={s.faceText}>{x}</Text></View>)}</View><View style={s.open}><Ionicons name="arrow-forward" color={DEEP} size={20}/></View></View></LinearGradient></TouchableOpacity>
<View style={s.quickRow}><TouchableOpacity style={s.quick} onPress={()=>router.push('/create-trip')}><Ionicons name="add-circle-outline" size={25} color={BLUE}/><Text style={s.quickText}>New trip</Text></TouchableOpacity><TouchableOpacity style={s.quick}><Ionicons name="people-outline" size={25} color={BLUE}/><Text style={s.quickText}>Join group</Text></TouchableOpacity><TouchableOpacity style={s.quick}><Ionicons name="map-outline" size={25} color={BLUE}/><Text style={s.quickText}>Routes</Text></TouchableOpacity></View>
<View style={s.sectionHead}><Text style={s.sectionTitle}>Explore Sri Lanka</Text><Text style={s.link}>See all</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{destinations.map(d=><TouchableOpacity key={d.name} style={s.destination}><View style={s.destinationIcon}><Ionicons name={d.icon} size={28} color={BLUE}/></View><View style={{flex:1}}><Text style={s.destinationName}>{d.name}</Text><Text style={s.destinationNote}>{d.note}</Text></View><Ionicons name="navigate-outline" color={BLUE} size={19}/></TouchableOpacity>)}</ScrollView>
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8FAFC'},page:{padding:20,paddingBottom:40},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:24},avatar:{width:48,height:48,borderRadius:18,backgroundColor:DEEP,alignItems:'center',justifyContent:'center'},avatarText:{color:'white',fontWeight:'800',fontSize:17},eyebrow:{fontSize:10,letterSpacing:1.5,color:'#64748B',fontWeight:'700'},heading:{fontSize:25,fontWeight:'800',color:'#0F172A'},iconButton:{width:44,height:44,borderRadius:16,backgroundColor:'white',alignItems:'center',justifyContent:'center'},search:{height:58,borderRadius:20,backgroundColor:'white',flexDirection:'row',alignItems:'center',paddingLeft:17,paddingRight:8,gap:10},searchInput:{flex:1,fontSize:15,color:'#0F172A'},filter:{width:42,height:42,borderRadius:15,backgroundColor:BLUE,alignItems:'center',justifyContent:'center'},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:27,marginBottom:13},sectionTitle:{fontSize:20,fontWeight:'800',color:'#0F172A'},link:{fontSize:13,fontWeight:'700',color:BLUE},hero:{height:290,borderRadius:30,padding:20},heroTop:{flexDirection:'row',justifyContent:'space-between'},pill:{flexDirection:'row',alignItems:'center',backgroundColor:'rgba(255,255,255,.16)',paddingHorizontal:12,paddingVertical:8,borderRadius:30},pillText:{color:'white',fontWeight:'700',fontSize:12},heroLabel:{fontSize:10,letterSpacing:2,color:'#BFDBFE',fontWeight:'800'},heroTitle:{color:'white',fontSize:29,fontWeight:'900',marginTop:3},heroMeta:{color:'#DBEAFE',fontSize:13,marginTop:5},routeMini:{flexDirection:'row',alignItems:'center',gap:6,marginTop:12,paddingTop:11,borderTopWidth:1,borderTopColor:'rgba(255,255,255,.18)'},routeText:{color:'#EFF6FF',fontSize:11,flex:1,fontWeight:'600'},routeKm:{color:'white',fontSize:11,fontWeight:'800'},heroBottom:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:14},faces:{flexDirection:'row'},face:{width:34,height:34,borderRadius:17,backgroundColor:'rgba(255,255,255,.2)',borderWidth:1,borderColor:'rgba(255,255,255,.4)',alignItems:'center',justifyContent:'center',marginRight:-5},faceText:{color:'white',fontWeight:'800',fontSize:11},open:{width:40,height:40,borderRadius:16,backgroundColor:'white',alignItems:'center',justifyContent:'center'},quickRow:{flexDirection:'row',gap:10,marginTop:16},quick:{flex:1,backgroundColor:'white',borderRadius:20,paddingVertical:16,alignItems:'center',gap:7},quickText:{fontSize:11,fontWeight:'700',color:'#334155'},destination:{width:220,height:108,borderRadius:24,backgroundColor:'white',padding:14,flexDirection:'row',alignItems:'center',gap:12},destinationIcon:{width:55,height:55,borderRadius:18,backgroundColor:LIGHT,alignItems:'center',justifyContent:'center'},destinationName:{fontSize:17,fontWeight:'800',color:'#0F172A'},destinationNote:{fontSize:11,color:'#64748B',marginTop:3}});