'use client';
import { useState } from 'react';
import { Map, CalendarDays, Users, WalletCards, MessageCircle, Plus, Search, Route, Compass, Bell } from 'lucide-react';

const itinerary=[['08:00','Breakfast in Kandy','Cafe • 1h'],['09:30','Temple of the Tooth','Attraction • 1h 30m'],['12:15','Kandy → Nuwara Eliya','Drive • 77 km • 2h 25m'],['15:00','Gregory Lake','Activity • 1h 30m'],['18:30','Check-in & dinner','Hotel • Nuwara Eliya']];
export default function Home(){const[tab,setTab]=useState('Itinerary');return <main className="shell">
<header className="topbar"><div className="brand"><span className="brandmark"><Compass size={20}/></span>TripFlow</div><nav className="nav"><button className="active">My trips</button><button>Explore</button><button>Saved places</button></nav><div className="top-actions"><button className="ghost"><Bell size={18}/></button><button className="primary"><Plus size={16}/> New trip</button><div className="avatar">M</div></div></header>
<section className="hero"><div className="hero-row"><div><div className="eyebrow">SRI LANKA • OCT 13–16, 2026</div><h1>Highlands road trip</h1><p>Colombo → Kandy → Nuwara Eliya → Ella • 4 travelers</p></div><div className="stats"><div className="stat"><small>TOTAL DISTANCE</small><strong>247 km</strong></div><div className="stat"><small>DRIVE TIME</small><strong>7h 25m</strong></div><div className="stat"><small>BUDGET</small><strong>LKR 120K</strong></div></div></div></section>
<section className="workspace">
<div className="panel"><div className="panel-head"><h2>Trip planner</h2><button className="add"><Plus size={14}/> Add</button></div><div className="tabs">{['Itinerary','Reservations','Checklist'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'on':''}>{x}</button>)}</div><div className="days"><div className="day-title"><div><div className="eyebrow" style={{color:'#2563eb'}}>DAY 2 • TUE, OCT 14</div><h3>Kandy → Nuwara Eliya</h3></div><button className="add">Optimize</button></div>{itinerary.map((x,i)=><div className="stop" key={x[1]}><div className="time">{x[0]}</div><div className="stop-card"><strong>{x[1]}</strong><p>{x[2]}</p></div><div className="distance">{i>0&&i<4?`${[3,77,4][i-1]||''} km`:''}</div></div>)}</div></div>
<div className="panel"><div className="panel-head"><h2><Map size={17}/> Route map</h2><button className="add"><Route size={14}/> Directions</button></div><div className="map"><div className="road r1"/><div className="road r2"/><div className="road r3"/><div className="route"/><div className="pin a"><span>A</span></div><div className="pin b"><span>B</span></div><div className="pin c"><span>C</span></div><div className="pin d"><span>D</span></div><div className="map-search"><input placeholder="Search attractions, restaurants, hotels or a city..."/><button><Search size={17}/></button></div><div className="map-summary"><div><small>DAY DISTANCE</small><b>84 km</b></div><div><small>TRAVEL TIME</small><b>2h 42m</b></div><div><small>STOPS</small><b>5</b></div></div></div></div>
<aside className="right"><div className="panel card"><h3><Users size={16}/> Tripmates</h3>{[['M','Manuja','Owner'],['S','Sahan','Editor'],['N','Nethmi','Member'],['A','Ashen','Member']].map(x=><div className="member" key={x[1]}><div className="avatar">{x[0]}</div><div><b>{x[1]}</b><br/><small>{x[2]}</small></div></div>)}<button className="add"><Plus size={14}/> Invite traveler</button></div><div className="panel card"><h3><WalletCards size={16}/> Budget</h3><div className="suggestion"><strong>LKR 72,450 of 120,000</strong><p>Accommodation 38K • Food 16K • Transport 12K • Activities 6.4K</p></div></div><div className="panel card"><h3>Group suggestions</h3><div className="suggestion"><strong>Add Nine Arches Bridge</strong><p>Sahan • “Best around early morning.”</p><div className="votes"><button>👍 3</button><button>💬 2</button><button>+ Plan</button></div></div></div><div className="panel chat"><div className="panel-head"><h2><MessageCircle size={16}/> Trip chat</h2></div><div className="messages"><div className="msg">Sahan: Shall we leave Kandy by noon?</div><div className="msg me">Yes, I moved the lake stop earlier.</div><div className="msg">Nethmi: Perfect. I saved a cafe near Gregory Lake.</div></div><div className="compose"><input placeholder="Message your tripmates..."/><button>Send</button></div></div></aside>
</section><div className="footer-note">TripFlow prototype • Supabase, ImageKit, live routing and maps will be connected in the integration stage.</div></main>}
