'use client';
import {useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import {CalendarDays,Users,WalletCards,MessageCircle,Plus,Search,Route,Compass,Bell,MapPin,GripVertical,Hotel,Utensils,Camera,ChevronDown,Share2,MoreHorizontal} from 'lucide-react';
import type {TripStop} from '../components/TripMap';
const TripMap=dynamic(()=>import('../components/TripMap'),{ssr:false});
const initial:TripStop[]=[{name:'Colombo',lat:6.9271,lng:79.8612,type:'Starting point'},{name:'Kandy',lat:7.2906,lng:80.6337,type:'City'},{name:'Nuwara Eliya',lat:6.9497,lng:80.7891,type:'City'},{name:'Ella',lat:6.8667,lng:81.0466,type:'Destination'}];
const activities=[['08:00','Breakfast in Kandy','Cafe • 1h','food'],['09:30','Temple of the Tooth','Attraction • 1h 30m','place'],['12:15','Drive to Nuwara Eliya','77 km • 2h 25m','drive'],['15:00','Gregory Lake','Activity • 1h 30m','place'],['18:30','Hotel check-in','Nuwara Eliya','hotel']];
export default function Home(){const[stops]=useState(initial);const[day,setDay]=useState(2);const[query,setQuery]=useState('');const days=['Mon 13','Tue 14','Wed 15','Thu 16'];const mapStops=useMemo(()=>stops,[stops]);return <main className="shell">
<header className="topbar"><div className="brand"><span className="brandmark"><Compass size={20}/></span>TripFlow</div><nav className="nav"><button className="active">My trips</button><button>Explore</button><button>Saved</button></nav><div className="top-actions"><button className="ghost"><Bell size={18}/></button><button className="primary"><Plus size={16}/> New trip</button><div className="avatar">M</div></div></header>
<section className="triphead"><div><button className="backlink">← My trips</button><div className="triptitle"><div><h1>Highlands road trip</h1><p><CalendarDays size={14}/> Oct 13–16, 2026 · Sri Lanka · 4 travelers</p></div><div className="headbuttons"><button className="soft"><Users size={16}/> Invite</button><button className="soft"><Share2 size={16}/> Share</button><button className="soft"><MoreHorizontal size={16}/></button></div></div></div></section>
<div className="tripnav"><button className="active">Plan</button><button>Explore</button><button>Reservations</button><button>Budget</button><button>Checklist</button><button>Chat <span className="badge">3</span></button></div>
<section className="planner-layout"><aside className="itinerary-panel"><div className="daystrip">{days.map((d,i)=><button key={d} onClick={()=>setDay(i+1)} className={day===i+1?'active':''}><small>DAY {i+1}</small><b>{d}</b></button>)}</div><div className="daycontent"><div className="dayheader"><div><small>DAY {day}</small><h2>{day===2?'Kandy → Nuwara Eliya':'Trip itinerary'}</h2></div><button className="soft"><Route size={15}/> Optimize</button></div><div className="day-summary"><span>84 km</span><span>2h 42m travel</span><span>5 stops</span></div>{activities.map((a,i)=><div className="activity" key={a[1]}><div className="activity-time">{a[0]}</div><div className="timeline"><span className={a[3]}/>{i<activities.length-1&&<i/>}</div><div className="activity-card"><div className="activity-icon">{a[3]==='food'?<Utensils/>:a[3]==='hotel'?<Hotel/>:a[3]==='drive'?<Route/>:<Camera/>}</div><div><b>{a[1]}</b><p>{a[2]}</p></div><GripVertical className="drag" size={17}/></div></div>)}<button className="add-stop"><Plus size={17}/> Add a place or activity</button></div></aside>
<section className="map-panel"><div className="map-tools"><div className="searchbox"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search places, hotels, restaurants..."/></div><button className="filterbtn">Nearby <ChevronDown size={14}/></button></div><TripMap stops={mapStops}/><div className="map-float"><b>Route overview</b><div><span><strong>247 km</strong><small>Total distance</small></span><span><strong>7h 25m</strong><small>Driving</small></span><button className="primary"><Route size={16}/> Directions</button></div></div></section>
<aside className="route-panel"><div className="side-section"><div className="side-title"><div><MapPin size={17}/> Route</div><button><Plus size={16}/></button></div><p className="hint">Drag stops to change the order. Your route and travel time will update.</p><div className="route-list">{stops.map((s,i)=><div className="route-stop" key={s.name}><div className="route-index">{i+1}</div><div className="route-name"><b>{s.name}</b><small>{s.type}{i<stops.length-1?' · next leg':''}</small></div><GripVertical size={17}/></div>)}</div><button className="full-soft"><Plus size={16}/> Add stop</button></div><div className="side-section compact"><div className="side-title"><div><Users size={17}/> Tripmates</div><button>Manage</button></div><div className="people"><div className="stack"><span>M</span><span>S</span><span>N</span><span>A</span></div><p>4 people planning together</p></div></div><div className="side-section compact"><div className="side-title"><div><WalletCards size={17}/> Budget</div><button>Open</button></div><div className="budgetline"><b>LKR 72,450</b><span>of 120,000</span></div><div className="progress"><i/></div></div><div className="side-section compact"><div className="side-title"><div><MessageCircle size={17}/> Group chat</div><button>Open</button></div><div className="chat-preview"><b>Sahan</b><p>Shall we leave Kandy by noon?</p></div></div></aside></section>
</main>}
