import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const tabs = ['Plan','Places','Budget','Members','Chat'];
export default function TripScreen(){
 const [tab,setTab]=useState('Plan');
 return <SafeAreaView style={s.safe}>
  <View style={s.top}><TouchableOpacity onPress={()=>router.back()} style={s.icon}><Ionicons name="chevron-back" size={22}/></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Ella Weekend</Text><Text style={s.sub}>Oct 13 – Oct 15 • 4 travelers</Text></View><TouchableOpacity style={s.icon}><Ionicons name="person-add-outline" size={21}/></TouchableOpacity></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{tabs.map(x=><TouchableOpacity key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabOn]}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></TouchableOpacity>)}</ScrollView>
  {tab==='Plan'?<Plan/>:tab==='Members'?<Members/>:tab==='Chat'?<Chat/>:<Empty title={tab} />}
 </SafeAreaView>
}
function Plan(){return <ScrollView contentContainerStyle={s.body}><View style={s.dayHead}><View><Text style={s.day}>Day 1</Text><Text style={s.date}>MONDAY • OCT 13</Text></View><TouchableOpacity style={s.add}><Ionicons name="add" color="white" size={19}/><Text style={s.addText}>Add</Text></TouchableOpacity></View>{[['08:00','Breakfast in Ella','restaurant-outline'],['09:30','Nine Arches Bridge','camera-outline'],['12:30','Little Adam’s Peak','trail-sign-outline'],['18:00','Group dinner','people-outline']].map((x,i)=><View style={s.event} key={x[1]}><View style={s.timeCol}><Text style={s.time}>{x[0]}</Text><View style={s.line}/></View><View style={s.eventCard}><View style={s.eventIcon}><Ionicons name={x[2] as any} size={21} color="#176D62"/></View><View style={{flex:1}}><Text style={s.eventTitle}>{x[1]}</Text><Text style={s.eventSub}>{i===1?'Suggested by Sahan • 3 votes':'Planned activity'}</Text></View><Ionicons name="ellipsis-horizontal" size={20} color="#84908B"/></View></View>)}</ScrollView>}
function Members(){return <ScrollView contentContainerStyle={s.body}><Text style={s.day}>Trip members</Text><Text style={s.muted}>Plan together and control who can edit the itinerary.</Text>{[['M','Manuja','Owner'],['S','Sahan','Editor'],['N','Nethmi','Member'],['A','Ashen','Member']].map(m=><View style={s.member} key={m[1]}><View style={s.avatar}><Text style={s.avatarText}>{m[0]}</Text></View><View style={{flex:1}}><Text style={s.memberName}>{m[1]}</Text><Text style={s.muted}>{m[2]}</Text></View><Ionicons name="chevron-forward" color="#8B948F" size={18}/></View>)}</ScrollView>}
function Chat(){return <View style={{flex:1}}><ScrollView contentContainerStyle={s.body}><Text style={s.day}>Group chat</Text><Text style={s.muted}>Messages will become realtime when Supabase is connected.</Text><Bubble name="Sahan" text="Can we add Nine Arches Bridge before breakfast gets too late?"/><Bubble name="You" text="Yes. I moved it to 9:30. Vote on the suggestion too." mine/><Bubble name="Nethmi" text="Perfect! I also saved a cafe nearby ☕"/></ScrollView><View style={s.composer}><TouchableOpacity><Ionicons name="add-circle-outline" size={26} color="#176D62"/></TouchableOpacity><TextInput placeholder="Message the group..." style={s.input}/><TouchableOpacity style={s.send}><Ionicons name="send" size={18} color="white"/></TouchableOpacity></View></View>}
function Bubble({name,text,mine=false}:{name:string,text:string,mine?:boolean}){return <View style={[s.bubbleWrap,mine&&{alignItems:'flex-end'}]}><Text style={s.bubbleName}>{name}</Text><View style={[s.bubble,mine&&s.bubbleMine]}><Text style={[s.bubbleText,mine&&{color:'white'}]}>{text}</Text></View></View>}
function Empty({title}:{title:string}){return <View style={s.empty}><Ionicons name={title==='Budget'?'wallet-outline':'map-outline'} size={54} color="#176D62"/><Text style={s.day}>{title}</Text><Text style={s.muted}>This workspace is ready for the next implementation stage.</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F7F2'},top:{flexDirection:'row',alignItems:'center',gap:12,padding:18},icon:{width:42,height:42,borderRadius:15,backgroundColor:'white',alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#14211E'},sub:{fontSize:11,color:'#7A827E',marginTop:2},tabs:{paddingHorizontal:18,gap:8,height:48},tab:{paddingHorizontal:17,height:38,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'white'},tabOn:{backgroundColor:'#173E42'},tabText:{fontSize:12,fontWeight:'700',color:'#64706B'},tabTextOn:{color:'white'},body:{padding:20,paddingBottom:35},dayHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:20},day:{fontSize:24,fontWeight:'900',color:'#14211E'},date:{fontSize:10,letterSpacing:1.2,color:'#89918D',fontWeight:'700',marginTop:4},add:{flexDirection:'row',gap:4,backgroundColor:'#176D62',paddingHorizontal:14,paddingVertical:10,borderRadius:15},addText:{color:'white',fontWeight:'800'},event:{flexDirection:'row',minHeight:94},timeCol:{width:52,alignItems:'center'},time:{fontSize:11,fontWeight:'800',color:'#53605B'},line:{width:1,backgroundColor:'#D8DDDA',flex:1,marginTop:7},eventCard:{flex:1,height:76,backgroundColor:'white',borderRadius:20,padding:12,flexDirection:'row',alignItems:'center',gap:11},eventIcon:{width:43,height:43,borderRadius:14,backgroundColor:'#E6F2EE',alignItems:'center',justifyContent:'center'},eventTitle:{fontSize:14,fontWeight:'800',color:'#1C2925'},eventSub:{fontSize:10,color:'#7D8782',marginTop:4},muted:{fontSize:12,color:'#7A827E',lineHeight:18,marginTop:4,marginBottom:18},member:{backgroundColor:'white',borderRadius:20,padding:13,flexDirection:'row',alignItems:'center',gap:12,marginBottom:10},avatar:{width:46,height:46,borderRadius:16,backgroundColor:'#173E42',alignItems:'center',justifyContent:'center'},avatarText:{color:'white',fontWeight:'900'},memberName:{fontSize:14,fontWeight:'800'},bubbleWrap:{marginTop:14,alignItems:'flex-start'},bubbleName:{fontSize:10,fontWeight:'800',color:'#7B8580',marginBottom:5},bubble:{maxWidth:'82%',padding:13,borderRadius:18,backgroundColor:'white'},bubbleMine:{backgroundColor:'#176D62'},bubbleText:{fontSize:13,lineHeight:19,color:'#26332F'},composer:{flexDirection:'row',alignItems:'center',gap:10,padding:12,paddingHorizontal:18,backgroundColor:'white'},input:{flex:1,height:44,borderRadius:16,backgroundColor:'#F1F3F0',paddingHorizontal:14},send:{width:42,height:42,borderRadius:15,backgroundColor:'#176D62',alignItems:'center',justifyContent:'center'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:40,gap:10}});